In [1]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])
print(a)

b = a.reshape(2, 3)
print(b)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [2]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(a.ravel())

[1 2 3 4 5 6]


In [5]:
a.resize(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]
